name: relay

include:
  - path: docker/database/compose.yml
    env_file: docker/database/container/.env.local
  - path: docker/messaging/compose.yml
    env_file: docker/messaging/container/.env.local

volumes:
  relay-postgres-data:
    driver: local
    name: relay-postgres-data
  relay-queues-data:
    driver: local
    name: relay-queues-data

networks:
  relay-network:
    driver: bridge
    name: relay-network
